name: Deploy Cloud Function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: reroll-board-games
          export_default_credentials: true
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            config:reroll-board-games/config-production
      - run: echo "::add-mask::${{ steps.secrets.outputs.config }}"
      - run: npm install
      - run: npm run compile
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: telegramsync
          region: us-central1
          runtime: nodejs14
          env_vars: CONFIG=${{ steps.secrets.outputs.config }}
